### ISSUE TITLE
wishlist: networks

### ISSUE THREAD

**Issue by tianon** [infosiftr/hocker#6]
One glaring point where hocker is a bit hard to use is `docker network`.  It's easy enough to create a shared script that multiple hockers source (via `$scriptDir`) that does idempotent `docker network create`, but it's _really_ annoying to do idempotent `docker network connect` (since it fails if the thing you're trying to connect is already connected, and the only way to check is to either inspect the network and enumerate the list of containers, or inspect the container and enumerate the list of networks).

To that end, I'd propose adding something like the following:
```bash
# create a network if it doesn't already exist
hocker_network_create some-network --flag --flag --flag ...
# (only proposing adding this for simplicity, given that it'll make hocker scripts shorter/simpler)

# join a network if we aren't already joined
hocker_network_connect [--container some-container] some-network --flag --flag --flag ...
# (flags at the end so that we can avoid re-implementing Docker's own parsing, similar to how we do for "hocker_run" having the image name first)
```

That way, hocker could instead implement the logic of inspecting and looping over the container's networks to ensure it's not already connected. :+1:

**Comment by tianon** [comment]
(I was going to suggest things around `--link`, but I think #5 already covers those as much as we could really consider doing -- we should focus on networks since they're more in line with how hocker expects to work, ala dependencies are a myth / must be handled by the application itself with connect-fail-retry loops. :+1:)

**Comment by tianon** [comment]
Another option is flags on `hocker_run`, but then arguments like `--alias` are harder to support, so IMO the approach I've proposed is simpler and more flexible.

**Comment by yosifkit** [comment]
Just to write my thought process out so that we can have a reference:

- what about detecting if the network flags have changed and deleting/recreating it (like our "smart" restart)
- but the smart restart doesn't look at any of the docker args
- other containers might already be in that network and we would have to remove all of them before deleting the netwotrk
- conclusion, that's too complex :disappointed:

**Comment by yosifkit** [comment]
`hocker_network_create` and `hocker_network_connect` seem fine, but I am not sure how the user would easily update their network configuration if it is already created :cry:

**Comment by tianon** [comment]
Same way they update their containers -- we can't really do `-f`, since removing the network requires removing ALL containers (and we can't recreate them), so that's left to the admin.  Maybe at some point we create separate helpers to do that sort of stuff easier?  For now I'd like to keep to minimum viable so we can keep moving forward without too much complexity and without locking ourselves in too much on design.
